[package]
name = "sb_linker_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
bpaf = { version = "0.8.1", features = ["derive"] }
toml = "0.8.23"
sb_linker = { path = "./linker" }

[workspace]
resolver = "2"
members = [
    "./linker",
]

[workspace.dependencies]
anyhow = "1.0.98"
thiserror = "2.0.12"
serde = "1.0.219"
serde_cbor = "0.11.2"
