[package]
name = "sb_linker_asmgen"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
sb_asm = { workspace = true }
sb_linker_obj = { path = "../obj" }
